name: "Test"
on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'

  pull_request:
    types: [ opened, synchronize ]
    paths-ignore:
      - '*.md'
    branches:
      - master

  workflow_dispatch:

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.0

      - name: Install dependencies and run tests
        run: |
          go mod download
          go test -v ./... -coverpkg=./... -short -coverprofile=unit_coverage.out

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage
          path: unit_coverage.out

  code_coverage:
    name: "Code coverage report"
    if: github.event_name == 'pull_request' # Do not run when workflow is triggered by push to main branch
    runs-on: ubuntu-latest
    needs: test
    continue-on-error: true # not critical
    permissions:
      contents: read
      actions: read  # to download code coverage results from "test" job
      pull-requests: write # write permission needed to comment on PR
    steps:
      - uses: fgrosse/go-coverage-report@v1.1.1
        with:
          coverage-artifact-name: code-coverage
          coverage-file-name: unit_coverage.out